-- schema_mysql.sql
-- Tabla de usuarios
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100),
    role VARCHAR(20) DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla de establecimientos
CREATE TABLE IF NOT EXISTS establecimientos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    clee VARCHAR(255),
    nom_estab VARCHAR(255),
    raz_social VARCHAR(255),
    codigo_act VARCHAR(255),
    nombre_act VARCHAR(255),
    per_ocu INT,
    tipo_vial VARCHAR(255),
    nom_vial VARCHAR(255),
    tipo_v_e_1 VARCHAR(255),
    nom_v_e_1 VARCHAR(255),
    tipo_v_e_2 VARCHAR(255),
    nom_v_e_2 VARCHAR(255),
    tipo_v_e_3 VARCHAR(255),
    nom_v_e_3 VARCHAR(255),
    numero_ext VARCHAR(50),
    letra_ext VARCHAR(10),
    edificio VARCHAR(255),
    edificio_e VARCHAR(255),
    numero_int VARCHAR(50),
    letra_int VARCHAR(10),
    tipo_asent VARCHAR(255),
    nomb_asent VARCHAR(255),
    tipoCenCom VARCHAR(255),
    nom_CenCom VARCHAR(255),
    num_local VARCHAR(50),
    cod_postal VARCHAR(5),
    cve_ent VARCHAR(50),
    entidad VARCHAR(255),
    cve_mun VARCHAR(50),
    municipio VARCHAR(255),
    cve_loc VARCHAR(50),
    localidad VARCHAR(255),
    ageb VARCHAR(50),
    manzana VARCHAR(50),
    telefono VARCHAR(10),
    correoelec VARCHAR(100),
    www VARCHAR(255),
    tipoUniEco VARCHAR(255),
    latitud DECIMAL(10, 8),
    longitud DECIMAL(11, 8),
    fecha_alta DATE,
    INDEX idx_municipio (municipio),
    INDEX idx_cod_postal (cod_postal),
    INDEX idx_latlong (latitud, longitud)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;